<script setup lang="ts">
const { site } = useAppConfig()

const title = `Changelog — ${site.name}`
const description = 'Every shipped version of this site, generated straight from GitHub Releases by the same CI/CD pipeline that deploys it.'

useSeoMeta({ title, description })

const { entries, error } = await useChangelog()
</script>

<template>
  <div>
    <UPageHero
      headline="Shipped via GitHub Actions → Vercel"
      title="Changelog"
      description="Every version of this site, straight from GitHub Releases — generated by the same pipeline shown in “How it ships”."
      orientation="horizontal"
    />

    <UPageSection>
      <div
        v-if="error"
        class="text-muted"
      >
        Couldn't load the changelog from GitHub right now. See the
        <UButton
          :to="`https://github.com/${site.github.repo}/releases`"
          target="_blank"
          variant="link"
          size="sm"
        >
          releases page
        </UButton>
        directly.
      </div>

      <UChangelogVersions v-else>
        <UChangelogVersion
          v-for="entry in entries"
          :key="entry.version"
          :title="entry.version"
          :date="entry.date"
          :to="entry.url"
          target="_blank"
          :badge="entry.badge"
        >
          <template #body>
            <MDC
              :value="entry.markdown"
              class="mt-4"
            />
          </template>
        </UChangelogVersion>
      </UChangelogVersions>
    </UPageSection>
  </div>
</template>
