<script setup lang="ts">
const { site } = useAppConfig()

const title = `Changelog — ${site.name}`
const description = 'Every shipped version of this site, generated straight from GitHub Releases by the same CI/CD pipeline that deploys it.'

useSeoMeta({ title, description })
defineOgImage('Terminal.satori', { title: 'Changelog', description })

const { entries, error } = await useChangelog()
</script>

<template>
  <div>
    <PageIntro
      path="~/changelog"
      title="Changelog"
      description="Every version of this site, straight from GitHub Releases — generated by the same pipeline shown in “How it ships”."
    />

    <section class="container-site py-16 sm:py-24">
      <p
        v-if="error"
        class="text-muted"
      >
        Couldn't load the changelog from GitHub right now. See the
        <a
          :href="`https://github.com/${site.github.repo}/releases`"
          target="_blank"
          class="text-highlighted underline underline-offset-4 hover:text-primary"
        >releases page</a>
        directly.
      </p>

      <ol v-else>
        <li
          v-for="entry in entries"
          :key="entry.version"
          class="grid gap-x-12 gap-y-4 border-t border-default py-10 lg:grid-cols-[11rem_1fr]"
        >
          <div class="lg:sticky lg:top-20 lg:self-start">
            <a
              :href="entry.url"
              target="_blank"
              class="flex items-center gap-2 font-mono text-lg font-medium text-highlighted hover:text-primary"
            >
              <span
                class="size-2"
                :class="entry.badge ? 'bg-primary' : 'border border-(--ui-border-accented)'"
              />
              {{ entry.version }}
            </a>
            <p class="mt-1 pl-4 font-mono text-xs text-dimmed">
              {{ entry.date }}<span
                v-if="entry.badge"
                class="text-primary"
              > · latest</span>
            </p>
          </div>

          <MDC
            :value="entry.markdown"
            class="min-w-0 text-sm text-muted [&_a]:text-toned [&_code]:font-mono [&_h2]:label [&_h2]:mt-6 [&_h2]:mb-2 [&_h2]:text-highlighted [&_h2:first-child]:mt-0 [&_h3]:label [&_h3]:mt-6 [&_h3]:mb-2 [&_h3]:text-highlighted [&_h3:first-child]:mt-0 [&_li]:my-1 [&_p]:my-2 [&_ul]:my-2"
          />
        </li>
      </ol>
    </section>
  </div>
</template>
